### ISSUE TITLE
Undefined overload property: `cache_clear_min_cap`

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#557]
Shows up in PHP error log when running the development branch.

``` text
[27-Aug-2015 23:41:09 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Undefined overload property: `cache_clear_min_cap`.' in /var/www/websharks/htdocs/wp-content/plugins/zencache-pro/src/includes/classes/AbsBase.php:116
Stack trace:
#0 /var/www/websharks/htdocs/wp-content/plugins/zencache-pro/src/includes/closures/Plugin/UserUtils.php(24): WebSharks\ZenCache\Pro\AbsBase->__get('cache_clear_min...')
#1 [internal function]: WebSharks\ZenCache\Pro\Plugin->WebSharks\ZenCache\Pro\{closure}()
#2 /var/www/websharks/htdocs/wp-content/plugins/zencache-pro/src/includes/classes/AbsBaseAp.php(55): call_user_func_array(Object(Closure), Array)
#3 /var/www/websharks/htdocs/wp-content/plugins/zencache-pro/src/includes/closures/Plugin/AdminBarUtils.php(45): WebSharks\ZenCache\Pro\AbsBaseAp->__call('currentUserCanC...', Array)
#4 /var/www/websharks/htdocs/wp-content/plugins/zencache-pro/src/includes/closures/Plugin/AdminBarUtils.php(45): WebSharks\ZenCache\Pro\Plugin->currentUserCanClearCache()
#5 [internal function]: WebSharks\ZenCache\Pro\Plugin->W in /var/www/websharks/htdocs/wp-content/plugins/zencache-pro/src/includes/classes/AbsBase.php on line 116
```

**Comment by raamdev** [comment]
@jaswsinc It looks like this might just have the wrong name; should `$self->cache_clear_min_cap` be `$self->clear_min_cap` instead? See:
https://github.com/websharks/zencache-pro/blob/000000-dev/src/includes/classes/Plugin.php#L91

**Comment by jaswrks** [comment]
> should $self->cache_clear_min_cap be $self->clear_min_cap instead?

Yeah, that's it!

**Comment by raamdev** [comment]
Cool. I'll fix this.

**Comment by raamdev** [comment]
Closed by https://github.com/websharks/zencache-pro/pull/135

**Comment by jaswrks** [comment]
Thanks!
