### ISSUE TITLE
Plugin Compatibility: AnsPress

### ISSUE THREAD

**Issue by raamdev** [wpsharks/comet-cache#737]
When Comet Cache Feed Caching is enabled (**Comet Cache → Plugin Options → RSS, RDF, and Atom Feeds**), a fatal error is produced when trying to activate the [AnsPress Question and Answer](https://wordpress.org/plugins/anspress-question-answer/) plugin (reproduced with Comet Cache Lite v160416):

```
PHP Fatal error: Uncaught Error: Undefined class constant 'CACHE_PATH_NO_SCHEME' in /home/wp-content/plugins/comet-cache/src/includes/classes/FeedUtils.php:232
Stack trace:

#0 /home/wp-content/plugins/comet-cache/src/includes/traits/Plugin/WcpFeedUtils.php(105): WebSharks\CometCache\Classes\FeedUtils->convertVariationsToHostCachePathRegexFrags(Array)
#1 /home/wp-content/plugins/comet-cache/src/includes/traits/Plugin/WcpPostUtils.php(95): WebSharks\CometCache\Classes\Plugin->autoClearXmlFeedsCache('blog')
#2 /home/wp-includes/plugin.php(525): WebSharks\CometCache\Classes\Plugin->autoClearPostCache(27353)
#3 /home/wp-includes/post.php(5510): do_action('clean_post_cach...', 27353, Object(WP_Post))
#4 /home/wp-includes/post.php(3282): clean_post_cache(Object(WP_Post))
#5 /home/wp-content/plugins/anspress-question-answer/includes/process-form.php(439): wp_insert_pos in /home/wp-content/plugins/comet-cache/src/includes/classes/FeedUtils.php on line 232
```

Disabling Comet Cache Feed Caching allows the AnsPress plugin to work as expected.

**Comment by raamdev** [comment]
This is not specific to AnsPress. This is a Comet Cache bug. See https://github.com/websharks/comet-cache/issues/739.

I'm closing this issue in favor of https://github.com/websharks/comet-cache/issues/739.
