### ISSUE TITLE
Since WordPress 5.2 an extension causes causes a fatal error

### ISSUE THREAD

**Issue by DidierV34** [wpsharks/comet-cache#933]
Since WordPress 5.2, a native feature allows you to detect if an extension or theme causes a fatal error on your site, and notifies you with this automatic email.

Here, WordPress has found an error with one of your extensions, "Comet Cache".

Détails de l’erreur ====================== Une erreur de type E_ERROR a été causée dans la ligne 227 du fichier /home/lengadoceq/www/wp-content/plugins/comet-cache/src/includes/traits/Shared/CacheDirUtils.php. Message d’erreur : Uncaught Exception: Unable to delete files. Rename failure on tmp directory: `/home/lengadoceq/www/wp-content/cache/comet-cache/cache-5cd4b3bcc8153667318668-tmp`. in /home/lengadoceq/www/wp-content/plugins/comet-cache/src/includes/traits/Shared/CacheDirUtils.php:227 Stack trace: #0 /home/lengadoceq/www/wp-content/plugins/comet-cache/src/includes/traits/Shared/CacheDirUtils.php(276): WebSharks\CometCache\Classes\AbsBaseAp->deleteFilesFromCacheDir('/^.+/ui', false) #1 /home/lengadoceq/www/wp-content/plugins/comet-cache/src/includes/traits/Shared/CacheDirUtils.php(61): WebSharks\CometCache\Classes\AbsBaseAp->deleteFilesFromHostCacheDir('/^.+/ui') #2 /home/lengadoceq/www/wp-content/plugins/comet-cache/src/includes/traits/Plugin/WcpUtils.php(82): WebSharks\CometCache\Classes\AbsBaseAp->clearFilesFromHostCacheDir('/^.+/ui') #3 /home/lengadoceq/www/wp-content/plugins/comet-cache/src/includes/traits/Plugin/WcpUtils.php(239): WebSharks\CometCache\Classes\Plugin->clearCache() #4 /home/lengadoceq/www/wp-content/plugins/

**Comment by clavaque** [comment]
Hi Didier. From what I can find, it sounds like Comet Cache is either having permissions issues performing the necessary cache cleanup, or your server doesn’t play nicely with atomic reads/writes.

We have seen this issue in the past and it has always ended up being related to the hosting environment. Can you check with your hosting company to see if they have any ideas?
